In [1]:
#
# loading libraries
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt


In [2]:
# load dataset
#   Training data
df_training = pd.read_csv('C:\\Users\\rivas\\OneDrive\\Documents\\JMR\\Education\\Springboard\\Projects\\Capstone1\\fashionmnisttrain.csv')

In [3]:
#   split data table into data Features (x) and class labels (y)
xdf_train = df_training.iloc[:, 1:]
ydf_train = df_training.iloc[:, :1]

In [4]:
#   Test data
#   split data table into data Features (x) and class labels (y)
df_test = pd.read_csv('C:\\Users\\rivas\\OneDrive\\Documents\\JMR\\Education\\Springboard\\Projects\\Capstone1\\fashionmnisttest.csv')

#   split data table into data Features (x) and class labels (y)
xdf_test = df_test.iloc[:, 1:]
ydf_test = df_test.iloc[:, :1]

In [6]:
#   Convert to numpy array
x_train = xdf_train.as_matrix()
y_train = ydf_train.as_matrix()
x_test = xdf_test.as_matrix()
y_test = ydf_test.as_matrix()

# Reshape array
y2_train = np.ravel( y_train[ : , 0] ) 
y2_test = np.ravel( y_test[ : , 0] ) 

In [7]:
x_train.shape


(60000, 784)

In [8]:
y2_train.shape

(60000,)

In [9]:
# Standardizing
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(x_train)

C:\Users\rivas\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
# PCA in scikit-learn  
from sklearn.decomposition import PCA

In [11]:
# Using 50 components
time_strt = datetime.now()
sklearn50_pca = PCA(n_components=50)
X_50 = sklearn50_pca.fit_transform(X_std)
time_fin = datetime.now()
print ("50 components: running time", (time_fin - time_strt))

50 components: running time 0:00:16.405929


In [12]:
time_strt = datetime.now()
sklearn600_pca = PCA(n_components=600)
X_600 = sklearn600_pca.fit_transform(X_std)
time_fin = datetime.now()
print ("600 components: running time", (time_fin - time_strt))

600 components: running time 0:01:19.607958


In [13]:
#**********************************************
# PCA - Prepare Test data for Predictive models
#
X_std = StandardScaler().fit_transform(x_test)


C:\Users\rivas\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
# Test data - Using 50 components
time_strt = datetime.now()
sklearn50_pca = PCA(n_components=50)
Xtest_50 = sklearn50_pca.fit_transform(X_std)
time_fin = datetime.now()
print ("50 components for Test data: running time", (time_fin - time_strt))

50 components for Test data: running time 0:00:01.513616


In [15]:
# Test data - Using 600 components
time_strt = datetime.now()
sklearn600_pca = PCA(n_components=600)
Xtest_600 = sklearn600_pca.fit_transform(X_std)
time_fin = datetime.now()
print ("600 components for Test data: running time", (time_fin - time_strt))

600 components for Test data: running time 0:00:11.352489


In [16]:
X_50.shape


(60000, 50)

In [17]:
X_600.shape

(60000, 600)

In [18]:
Xtest_50.shape


(10000, 50)

In [19]:
Xtest_600.shape

(10000, 600)

In [20]:
# Random Forest Classifier
# 1 - Import the model
from sklearn.ensemble import RandomForestClassifier


In [21]:
# 2 - Make an instance of the Model
RF_clf = RandomForestClassifier(n_jobs=2, random_state=0)


In [22]:
# Using PCA 50 (X_50) for training data
#
# 3 - Training the model on the Training data
#     fitting the model
time_strt = datetime.now()
RF_clf.fit(X_50, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))


Fitting Model: running time 0:00:07.005574


In [23]:
# 4 - Predict the response
time_strt = datetime.now()
RF_clf_predict = RF_clf.predict(Xtest_50)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))


Predict: running time 0:00:00.421125


In [24]:
# 5 - Evaluate accuracy
#     loading libraries
from sklearn.metrics import precision_score, \
    recall_score, confusion_matrix, classification_report, \
    accuracy_score, f1_score

print ('Accuracy:', accuracy_score(y2_test, RF_clf_predict))

Accuracy: 0.6914


In [25]:
print ('\n clasification report:\n', classification_report(y2_test,RF_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.68      0.74      0.71      1000
          1       0.91      0.91      0.91      1000
          2       0.47      0.58      0.52      1000
          3       0.75      0.75      0.75      1000
          4       0.50      0.44      0.47      1000
          5       0.72      0.74      0.73      1000
          6       0.40      0.33      0.36      1000
          7       0.75      0.76      0.75      1000
          8       0.87      0.88      0.88      1000
          9       0.84      0.79      0.81      1000

avg / total       0.69      0.69      0.69     10000



In [26]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, RF_clf_predict))


 confussion matrix:
 [[745  10  32  66  10   3 116   0  18   0]
 [ 21 905  15  42   2   0  13   0   2   0]
 [ 28   2 579   7 223   1 135   0  25   0]
 [ 76  62  22 747  34   1  52   0   6   0]
 [ 18   5 312  66 437   3 140   0  19   0]
 [  3   2  14   2   6 744   4 152  10  63]
 [182   7 234  63 142   5 330   0  37   0]
 [  1   0   0   0   0 153   0 755   5  86]
 [ 15   5  24   6  12  15  27   8 883   5]
 [  0   0   3   0   0 107   0  92   9 789]]


In [27]:
# Using PCA 600 (X_600) for training data
#
# 3 - Training the model on the Training data
#     fitting the model
time_strt = datetime.now()
RF_clf.fit(X_600, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))

Fitting Model: running time 0:00:23.764440


In [28]:
# 4 - Predict the response
time_strt = datetime.now()
RF_clf_predict = RF_clf.predict(Xtest_600)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))

Predict: running time 0:00:00.162009


In [29]:
# 5 - Evaluate accuracy
print ('Accuracy:', accuracy_score(y2_test, RF_clf_predict))

Accuracy: 0.5773


In [30]:
print ('\n clasification report:\n', classification_report(y2_test,RF_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.50      0.69      0.58      1000
          1       0.87      0.84      0.86      1000
          2       0.35      0.43      0.39      1000
          3       0.61      0.63      0.62      1000
          4       0.40      0.43      0.41      1000
          5       0.61      0.55      0.58      1000
          6       0.31      0.21      0.25      1000
          7       0.70      0.67      0.69      1000
          8       0.69      0.63      0.66      1000
          9       0.78      0.69      0.73      1000

avg / total       0.58      0.58      0.58     10000



In [31]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, RF_clf_predict))


 confussion matrix:
 [[688   9  55  87  20   9  93   2  33   4]
 [ 28 845  16  80   8   3  11   0   9   0]
 [ 89  16 426  25 270  19 109   1  36   9]
 [146  56  42 634  43   5  56   2  11   5]
 [ 65   8 268  70 429  11  99   5  42   3]
 [ 45   7  53  17  27 551  24 166  52  58]
 [235  14 220  81 174  16 214   5  40   1]
 [ 14   2  20  11  12 151  14 670  17  89]
 [ 60  10  73  22  72  40  53  15 629  26]
 [ 16   2  29  11  13  95  16  85  46 687]]


In [32]:
# Support Vector Machines (SVM)
# 1 - Import the model
from sklearn import svm

# 2 - Make an instance of the Model
SVM_clf = svm.SVC(gamma=0.001, C=100.)


In [33]:
# 3 - Training the model with PCA - 50 components
#     fitting the model
time_strt = datetime.now()
SVM_clf.fit(X_50, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))


Fitting Model: running time 0:02:56.270764


In [34]:
# 4 - Predict the response
time_strt = datetime.now()
SVM_clf_predict = SVM_clf.predict(Xtest_50)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))


Predict: running time 0:00:28.331564


In [35]:
# 5 - Evaluate accuracy
print ('Accuracy:', accuracy_score(y2_test, SVM_clf_predict))

Accuracy: 0.5893


In [36]:
print ('\n clasification report:\n', classification_report(y2_test,SVM_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.54      0.68      0.60      1000
          1       0.93      0.85      0.89      1000
          2       0.36      0.37      0.37      1000
          3       0.62      0.51      0.56      1000
          4       0.50      0.29      0.37      1000
          5       0.56      0.63      0.59      1000
          6       0.29      0.42      0.34      1000
          7       0.67      0.64      0.65      1000
          8       0.88      0.88      0.88      1000
          9       0.73      0.62      0.67      1000

avg / total       0.61      0.59      0.59     10000



In [37]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, SVM_clf_predict))


 confussion matrix:
 [[679   3  35  69  11   0 186   0  17   0]
 [ 89 851   5  42   3   1   9   0   0   0]
 [ 28   5 367  30 165   0 394   0  11   0]
 [188  47  54 514  16   0 180   0   1   0]
 [ 40   2 313  96 295   0 241   0  13   0]
 [  9   0   7   1   1 634   6 243  16  83]
 [171   3 214  73  85   0 419   0  35   0]
 [  0   0   0   0   0 196   0 637  23 144]
 [ 42   2  11   2  18   8  32   4 877   4]
 [  2   0   0   0   0 303   0  73   2 620]]


In [38]:
# 3 - Training the model with PCA - 600 components
#     fitting the model
time_strt = datetime.now()
SVM_clf.fit(X_600, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))

Fitting Model: running time 0:15:10.329510


In [39]:
# 4 - Predict the response
time_strt = datetime.now()
SVM_clf_predict = SVM_clf.predict(Xtest_600)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))


Predict: running time 0:04:53.874098


In [40]:
# 5 - Evaluate accuracy
print ('Accuracy:', accuracy_score(y2_test, SVM_clf_predict))


Accuracy: 0.6967


In [41]:
print ('\n clasification report:\n', classification_report(y2_test,SVM_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.62      0.78      0.69      1000
          1       0.99      0.89      0.94      1000
          2       0.42      0.44      0.43      1000
          3       0.70      0.71      0.71      1000
          4       0.55      0.43      0.49      1000
          5       0.83      0.71      0.77      1000
          6       0.38      0.37      0.37      1000
          7       0.78      0.84      0.81      1000
          8       0.88      0.94      0.91      1000
          9       0.83      0.85      0.84      1000

avg / total       0.70      0.70      0.70     10000



In [42]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, SVM_clf_predict))


 confussion matrix:
 [[777   0  23  39   5   0 134   0  22   0]
 [ 28 892   8  57   3   0   9   0   2   1]
 [ 18   1 443  19 196   0 307   0  16   0]
 [186   9  21 709  19   0  56   0   0   0]
 [ 17   0 334 131 435   0  72   0  11   0]
 [  0   0   2   1   2 713   9 171  28  74]
 [221   0 214  45 123   0 367   0  30   0]
 [  0   0   0   0   0  64   0 842   3  91]
 [  8   0   6   9  10   2  15   5 942   3]
 [  0   0   0   0   0  80   1  59  13 847]]


In [43]:
# Neural Networks Classifier
# 1 - Import the model
from sklearn.neural_network import MLPClassifier


In [44]:
# 2 - Make an instance of the Model
MLP_clf = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [45]:
# 3 - Training the model with PCA - 50 components
#     fitting the model
time_strt = datetime.now()
MLP_clf.fit(X_50, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))

Fitting Model: running time 0:00:47.391089


In [47]:
# 4 - Predict the response
time_strt = datetime.now()
MLP_clf_predict = MLP_clf.predict(Xtest_50)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))

Predict: running time 0:00:00.046001


In [48]:
# 5 - Evaluate accuracy
print ('Accuracy:', accuracy_score(y2_test, MLP_clf_predict))


Accuracy: 0.6306


In [49]:
print ('\n clasification report:\n', classification_report(y2_test,MLP_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.66      0.77      0.71      1000
          1       0.93      0.90      0.91      1000
          2       0.34      0.31      0.32      1000
          3       0.79      0.76      0.78      1000
          4       0.48      0.48      0.48      1000
          5       0.68      0.64      0.66      1000
          6       0.29      0.30      0.30      1000
          7       0.59      0.82      0.69      1000
          8       0.83      0.92      0.87      1000
          9       0.76      0.42      0.54      1000

avg / total       0.64      0.63      0.63     10000



In [50]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, MLP_clf_predict))


 confussion matrix:
 [[767  10  24  46   4   0 123   1  25   0]
 [ 22 896  16  51   4   0   9   0   1   1]
 [ 10   3 306   9 270   0 370   1  31   0]
 [ 97  26  26 763  23   0  58   0   6   1]
 [ 22   6 307  39 476   0 136   0  14   0]
 [  6   6   8   6   0 637   9 194  56  78]
 [222   4 197  46 200   0 303   0  28   0]
 [  1   0   0   0   0 119   0 822  13  45]
 [ 10   1   9   6  16  13  21   3 916   5]
 [  3  13   1   2   0 174   0 376  11 420]]


In [51]:
# ********************************************************************************
# 3 - Training the model with PCA - 600 components
#     fitting the model
time_strt = datetime.now()
MLP_clf.fit(X_600, y2_train)
time_fin = datetime.now()
print ("Fitting Model: running time", (time_fin - time_strt))

Fitting Model: running time 0:01:41.088657


In [52]:
# 4 - Predict the response
time_strt = datetime.now()
MLP_clf_predict = MLP_clf.predict(Xtest_600)
time_fin = datetime.now()
print ("Predict: running time", (time_fin - time_strt))

Predict: running time 0:00:00.160863


In [53]:
# 5 - Evaluate accuracy
print ('Accuracy:', accuracy_score(y2_test, MLP_clf_predict))


Accuracy: 0.6024


In [54]:
print ('\n clasification report:\n', classification_report(y2_test,MLP_clf_predict))


 clasification report:
              precision    recall  f1-score   support

          0       0.67      0.69      0.68      1000
          1       0.92      0.90      0.91      1000
          2       0.42      0.43      0.43      1000
          3       0.67      0.76      0.71      1000
          4       0.44      0.45      0.44      1000
          5       0.54      0.44      0.49      1000
          6       0.28      0.27      0.28      1000
          7       0.57      0.62      0.60      1000
          8       0.81      0.79      0.80      1000
          9       0.67      0.68      0.68      1000

avg / total       0.60      0.60      0.60     10000



In [55]:
print ('\n confussion matrix:\n',confusion_matrix(y2_test, MLP_clf_predict))


 confussion matrix:
 [[687   9  31  90   6   1 156   0  18   2]
 [ 14 898  12  50   3   0  22   0   1   0]
 [ 14   3 433  20 262   0 240   1  27   0]
 [ 83  39  15 757  46   0  50   0  10   0]
 [ 34  12 261  85 447   2 139   0  20   0]
 [ 12   2   4  38   4 444  28 270  29 169]
 [160   4 231  73 228   3 266   0  30   5]
 [  2   1   2   3   0 223   0 622  50  97]
 [ 15   5  42   9  12  21  23  20 788  65]
 [  0   1   6   0   1 125  10 172   3 682]]
